### ISSUE TITLE
Firefox Context right click searches brings up extensions window

### ISSUE THREAD

**Issue by clapierre** [benetech/Imageshare-Extensions#36]
When right clicking on a word and performing an Imageshare Standard or Advance Search a new tab appears of 
about:addons which you are taken to showing you the Imageshare Options, and then after a second or so a 3rd tab appears and you are taken to the Imageshare Results page.

No idea why we are getting this about:addons page showing up.  This doesn't happen if you use the toolbar Imageshare "Run Standard Search"

**Comment by sinabahram** [comment]
This is the correct behavior for advanced but not for standard. For advanced it is correct because you have not configured your advanced search settings yet. Think of it as how advanced find works on all platforms/apps, but for standard, this absolutely should not be happening.

**Comment by clapierre** [comment]
@sinabahram I am fine if it brings it up in the advance search case if you haven't configured it yet, that makes a lot of sense.  That is not what I am seeing and since I can't pick or save my advance settings I can't test this fully until that happens.

But totally agree with you on that point.

**Comment by LE0616** [comment]
@clapierre I'm going to work on this one right now. I'm noticing that Options opening when there's no criteria is not consistent across browsers. It's only happening in Firefox atm and the notification isn't clear that this should be the expectation either. I'll drop a note here when that's working correctly across browsers.

**Comment by LE0616** [comment]
ok all set. I still need to test in Safari, but this feature should be available in branch main by morning. I'll be merging my current branch tonight.

**Comment by LE0616** [comment]
I'm leaving Options opening on it's own in Firefox as a bug though for now so don't close this issue just yet.

**Comment by clapierre** [comment]
I just puled the latest, brought up Firefox Dev Edition, loaded the manifest from the src-chrome-firefox but selecting some text and doing a standard search still brought up the extensions page before moving onto the Imageshare results page.

Wasn't sure if this was fully addressed, the comments seemed to indicate it should be working in FF but needed to be tested yet in Safari.  I haven't moved onto Safari as Sina thought lets make sure everything is working in Chrome/FF first.

**Comment by sinabahram** [comment]
@clapierre , sorry but from @LE0616 's comment "I'm leaving Options opening on it's own in Firefox as a bug though for now so don't close this issue just yet.", let's have you hold off on testing.

**Comment by clapierre** [comment]
@LE0616 I assume this is a work in progress as Sina stated but in Chrome Canary the Options Page is blank and when I go back to the plugin itself which I updated today after  Empty string validation (#44) was merged into main I see the following error:

Uncaught TypeError: Cannot read property 'addEventListener' of null
with this code highlighted.
** advSaveButton.addEventListener("click",**

**Comment by LE0616** [comment]
There was still a merge pending for the Options page, creating some blocks. Try it now. 

As for the Firefox issue opening the options page at unwanted times. Yes that issue is still in process. Job has a working theory on that issue and is going to implement the fix when he's in there creating build targets to consolidate the code. I'm assuming that he'll either comment here or simply close this issue when it's complete.

**Comment by clapierre** [comment]
I can confirm the option page is now loading correctly.
Once the advance options are saved I get the following results when doing an advance search

Canary attempts the advance search now without bringing up the options pane anymore, which is correct and expected.

FF first brings up the options tab, then immediately brings up another tab with the imageshare results.  So better, but ideally it shouldn't be bringing up that options tab at all right?

**Comment by LE0616** [comment]
Correct, unless it's the first time the user is clicking Advanced and they
have not yet chosen Advanced Criteria. In this case, the options should
open and the notification should explain why. If there are advanced
criteria saved, options should not open, and the advanced search should
proceed normally.

**Comment by LE0616** [comment]
Fixed in branch L-final-edits. Will be merged to main Wed 5/18.
